#!/bin/sh

link=$1

if [ -z "$link" ]; then
  osascript -e 'tell app "Finder" to display alert  "Please provide a link as an argument."'
  exit 1
fi

# Copy the link to the clipboard
echo "$link" | pbcopy

exit 0
